run:
  skip-dirs:
    - build
    - cmake
    - doc
    - kindlegen
    - static
    - testdata
    - tools
    - vendor
  tests: false
  issues-exit-code: 0

linters:
  presets:
    - bugs
    - unused
    - style
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - whitespace
    - wsl
    - gomnd
    - nlreturn
    - wrapcheck
    - exhaustivestruct
  fast: false

linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 185
    # tab width in spaces. Default to 1.
    tab-width: 4
  gofmt:
    simplify: true
  funlen:
    lines: 250
    statements: 120
  dogsled:
    max-blank-identifiers: 3
  godot:
    scope: declarations
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "Subprocess launched with function call as argument or cmd arguments"
      linters:
        - gosec
    - text: "do not define dynamic errors"
      linters:
        - goerr113
    - text: "don't use ALL_CAPS in Go names"
      linters:
        - golint
    - text: "should not use ALL_CAPS in Go names"
      linters:
        - stylecheck
