name: gclpr release

on:
  create:
    tags:
    - "v*.*.*"

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install mingw-w64 resource compiler
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mingw-w64 binutils-mingw-w64-x86-64
          version: 1.0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build everything
        run: go tool task release

      - name: List results
        run: ls -lah release/

      - name: Upload release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: |
            gclpr.json
            release/gclpr_*.zip
